"""segunda migracion

Revision ID: 88934fd5e1cb
Revises: eee34329a130
Create Date: 2023-06-03 20:11:46.848414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88934fd5e1cb'
down_revision = 'eee34329a130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('usuario','usuarios')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('usuarios','usuario')
    # ### end Alembic commands ###
